import ENV from "../../../../config/default";

export const JWT_ACCESS_TOKEN_GENERATOR = ENV.JWT_ACCESS_TOKEN;
export const JWT_REFRESH_TOKEN_GENERATOR = ENV.JWT_REFRESH_TOKEN;
export const REFRESH_TOKEN_VERIFY = ENV.JWT_REFRESH_TOKEN;
